### ISSUE TITLE
Import Error in lib/roby/log/gui/relations_view/relations_config.rb:2

### ISSUE THREAD

**Issue by Rauldg** [rock-core/tools-roby#11]
```
rdominguez@RDOMINGUEZ:~/spacebot-rock/bundles/spacebot$ syskit browse
Bundles[INFO]: Active bundles: spacebot, rock, rock_ugv_nav
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- roby/log/gui/relations_view/relations_ui (LoadError)
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /home/rdominguez/spacebot-rock/tools/roby/lib/roby/log/gui/relations_view/relations_config.rb:2:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /home/rdominguez/spacebot-rock/tools/roby/lib/roby/log/gui/relations_view/relations_view.rb:4:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /home/rdominguez/spacebot-rock/tools/roby/lib/roby/log/gui/relations_view/relations_canvas.rb:7:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /home/rdominguez/spacebot-rock/tools/roby/lib/roby/gui/model_views/task.rb:1:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /home/rdominguez/spacebot-rock/tools/syskit/lib/syskit/gui/model_views.rb:2:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /home/rdominguez/spacebot-rock/tools/syskit/lib/syskit/gui/model_browser.rb:2:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /home/rdominguez/spacebot-rock/tools/syskit/lib/syskit/scripts/browse.rb:4:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /home/rdominguez/spacebot-rock/tools/syskit/bin/syskit:19:in `<main>'
```

If I remove the require, syskit browse starts but maybe it is not a good idea to remove it.

**Comment by doudou** [comment]
Should be working now.
