### ISSUE TITLE
writing through the interface server might cause a system shutdown

### ISSUE THREAD

**Issue by doudou** [rock-core/tools-roby#64]
```
Abr 06 20:02:14 ff-nav syskit[15152]: Roby[FATAL]: Application error in at_cycle_end
Abr 06 20:02:14 ff-nav syskit[15152]: Roby[FATAL]: No route to host (Errno::EHOSTUNREACH)
Abr 06 20:02:14 ff-nav syskit[15152]: Roby[FATAL]: = Backtrace
Abr 06 20:02:14 ff-nav syskit[15152]: Roby[FATAL]: =
Abr 06 20:02:14 ff-nav syskit[15152]: Roby[FATAL]:
Abr 06 20:02:14 ff-nav syskit[15152]: Roby[FATAL]:   <internal:prelude>:134:in `__write_nonblock'
Abr 06 20:02:14 ff-nav syskit[15152]: Roby[FATAL]:   <internal:prelude>:134:in `write_nonblock'
Abr 06 20:02:14 ff-nav syskit[15152]: Roby[FATAL]:   /home/flatfish/dev.bir.alpha/tools/roby/lib/roby/interface/droby_channel.rb:127:in `push_write_data'
Abr 06 20:02:14 ff-nav syskit[15152]: Roby[FATAL]:   /home/flatfish/dev.bir.alpha/tools/roby/lib/roby/interface/droby_channel.rb:122:in `write_packet'
Abr 06 20:02:14 ff-nav syskit[15152]: Roby[FATAL]:   /home/flatfish/dev.bir.alpha/tools/roby/lib/roby/interface/server.rb:25:in `block in initialize'
Abr 06 20:02:14 ff-nav syskit[15152]: Roby[FATAL]:   /home/flatfish/dev.bir.alpha/tools/roby/lib/roby/interface/interface.rb:531:in `block in notify_cycle_end'
Abr 06 20:02:14 ff-nav syskit[15152]: Roby[FATAL]:   /home/flatfish/dev.bir.alpha/tools/roby/lib/roby/interface/interface.rb:530:in `each'
Abr 06 20:02:14 ff-nav syskit[15152]: Roby[FATAL]:   /home/flatfish/dev.bir.alpha/tools/roby/lib/roby/interface/interface.rb:530:in `notify_cycle_end'
Abr 06 20:02:14 ff-nav syskit[15152]: Roby[FATAL]:   /home/flatfish/dev.bir.alpha/tools/roby/lib/roby/interface/interface.rb:122:in `block in initialize'
Abr 06 20:02:14 ff-nav syskit[15152]: Roby[FATAL]:   /home/flatfish/dev.bir.alpha/tools/roby/lib/roby/execution_engine.rb:229:in `call'
Abr 06 20:02:14 ff-nav syskit[15152]: Roby[FATAL]:   /home/flatfish/dev.bir.alpha/tools/roby/lib/roby/execution_engine.rb:716:in `block (2 levels) in call_poll_blocks'
Abr 06 20:02:14 ff-nav syskit[15152]: Roby[FATAL]:   /home/flatfish/dev.bir.alpha/tools/roby/lib/roby/droby/event_logging.rb:22:in `log_timepoint_group'
Abr 06 20:02:14 ff-nav syskit[15152]: Roby[FATAL]:   /home/flatfish/dev.bir.alpha/tools/roby/lib/roby/execution_engine.rb:715:in `block in call_poll_blocks'
Abr 06 20:02:14 ff-nav syskit[15152]: Roby[FATAL]:   /home/flatfish/dev.bir.alpha/tools/roby/lib/roby/execution_engine.rb:710:in `delete_if'
Abr 06 20:02:14 ff-nav syskit[15152]: Roby[FATAL]:   /home/flatfish/dev.bir.alpha/tools/roby/lib/roby/execution_engine.rb:710:in `call_poll_blocks'
Abr 06 20:02:14 ff-nav syskit[15152]: Roby[FATAL]:   /home/flatfish/dev.bir.alpha/tools/roby/lib/roby/execution_engine.rb:2227:in `block in cycle_end'
Abr 06 20:02:14 ff-nav syskit[15152]: Roby[FATAL]:   /home/flatfish/dev.bir.alpha/tools/roby/lib/roby/execution_engine.rb:581:in `gather_framework_errors'
Abr 06 20:02:14 ff-nav syskit[15152]: Roby[FATAL]:   /home/flatfish/dev.bir.alpha/tools/roby/lib/roby/execution_engine.rb:2226:in `cycle_end'
Abr 06 20:02:14 ff-nav syskit[15152]: Roby[FATAL]:   /home/flatfish/dev.bir.alpha/tools/roby/lib/roby/execution_engine.rb:2125:in `block in event_loop'
Abr 06 20:02:14 ff-nav syskit[15152]: Roby[FATAL]:   /home/flatfish/dev.bir.alpha/tools/roby/lib/roby/execution_engine.rb:2065:in `loop'
Abr 06 20:02:14 ff-nav syskit[15152]: Roby[FATAL]:   /home/flatfish/dev.bir.alpha/tools/roby/lib/roby/execution_engine.rb:2065:in `event_loop'
Abr 06 20:02:14 ff-nav syskit[15152]: Roby[FATAL]:   /home/flatfish/dev.bir.alpha/tools/roby/lib/roby/execution_engine.rb:1985:in `run'
Abr 06 20:02:14 ff-nav syskit[15152]: Roby[FATAL]:   /home/flatfish/dev.bir.alpha/tools/roby/lib/roby/app.rb:1732:in `block in run'
Abr 06 20:02:14 ff-nav syskit[15152]: Roby[FATAL]: =
```

**Comment by doudou** [comment]
This should be fixed in the roby3 branch already
