### ISSUE TITLE
Stable branch in Ubuntu 16.04 rock installation Error

### ISSUE THREAD

**Issue by Rauldg** [rock-core/tools-roby#68]
Starting from a new bootstrap using ubuntu 16.04 (ruby2.3) and stable branch. Following what was explained here [https://github.com/rock-core/autoproj/issues/144]. I run into this error when building roby.

```
    /usr/bin/ruby2.3 -S rake default
in directory /home/dfki.uni-bremen.de/rdominguez/rock/entern/05/tools/roby
a required gem seems to be not available, documentation generation disabled
  Ruby reported the following load error: cannot load such file -- webgen/webgentask
cd tmp/x86_64-linux-gnu/roby_marshalling/2.3.1
make
compiling ../../../../ext/roby_marshalling/dump.cc
In file included from /usr/include/ruby-2.3.0/ruby.h:33:0,
                 from ../../../../ext/roby_marshalling/dump.cc:1:
../../../../ext/roby_marshalling/dump.cc: In function ‘VALUE array_droby_dump(VALUE, VALUE)’:
/usr/include/ruby-2.3.0/ruby/ruby.h:1044:37: error: invalid conversion from ‘RArray*’ to ‘VALUE {aka long unsigned int}’ [-fpermissive]
 #define RARRAY_LEN(a) rb_array_len(a)
                                     ^
../../../../ext/roby_marshalling/dump.cc:84:21: note: in expansion of macro ‘RARRAY_LEN’
     for (i = 0; i < RARRAY_LEN(array); ++i)
                     ^
In file included from /usr/include/ruby-2.3.0/ruby.h:33:0,
                 from ../../../../ext/roby_marshalling/dump.cc:1:
/usr/include/ruby-2.3.0/ruby/ruby.h:2010:1: note:   initializing argument 1 of ‘long int rb_array_len(VALUE)’
 rb_array_len(VALUE a)
 ^
Makefile:207: recipe for target 'dump.o' failed
make: *** [dump.o] Error 1
rake aborted!
Command failed with status (2): [make...]
/home/dfki.uni-bremen.de/rdominguez/rock/entern/05/.gems/gems/rake-compiler-0.8.3/lib/rake/extensiontask.rb:112:in `block (2 levels) in define_compile_tasks'
/home/dfki.uni-bremen.de/rdominguez/rock/entern/05/.gems/gems/rake-compiler-0.8.3/lib/rake/extensiontask.rb:111:in `block in define_compile_tasks'
Tasks: TOP => default => compile => compile:x86_64-linux-gnu => compile:roby_marshalling:x86_64-linux-gnu => copy:roby_marshalling:x86_64-linux-gnu:2.3.1 => tmp/x86_64-linux-gnu/roby_marshalling/2.3.1/roby_marshalling.so
(See full trace by running task with --trace)
```

Running it with --trace this is the output:
```
a required gem seems to be not available, documentation generation disabled
  Ruby reported the following load error: cannot load such file -- webgen/webgentask
** Invoke default (first_time)
** Invoke compile (first_time)
** Invoke compile:x86_64-linux-gnu (first_time)
** Invoke compile:roby_marshalling:x86_64-linux-gnu (first_time)
** Invoke copy:roby_marshalling:x86_64-linux-gnu:2.3.1 (first_time)
** Invoke lib (first_time, not_needed)
** Invoke tmp/x86_64-linux-gnu/roby_marshalling/2.3.1/roby_marshalling.so (first_time)
** Invoke tmp/x86_64-linux-gnu/roby_marshalling/2.3.1/Makefile (first_time, not_needed)
** Invoke tmp/x86_64-linux-gnu/roby_marshalling/2.3.1 (first_time, not_needed)
** Invoke ext/roby_marshalling/extconf.rb (first_time, not_needed)
** Execute tmp/x86_64-linux-gnu/roby_marshalling/2.3.1/roby_marshalling.so
cd tmp/x86_64-linux-gnu/roby_marshalling/2.3.1
make
compiling ../../../../ext/roby_marshalling/dump.cc
In file included from /usr/include/ruby-2.3.0/ruby.h:33:0,
                 from ../../../../ext/roby_marshalling/dump.cc:1:
../../../../ext/roby_marshalling/dump.cc: In function ‘VALUE array_droby_dump(VALUE, VALUE)’:
/usr/include/ruby-2.3.0/ruby/ruby.h:1044:37: error: invalid conversion from ‘RArray*’ to ‘VALUE {aka long unsigned int}’ [-fpermissive]
 #define RARRAY_LEN(a) rb_array_len(a)
                                     ^
../../../../ext/roby_marshalling/dump.cc:84:21: note: in expansion of macro ‘RARRAY_LEN’
     for (i = 0; i < RARRAY_LEN(array); ++i)
                     ^
In file included from /usr/include/ruby-2.3.0/ruby.h:33:0,
                 from ../../../../ext/roby_marshalling/dump.cc:1:
/usr/include/ruby-2.3.0/ruby/ruby.h:2010:1: note:   initializing argument 1 of ‘long int rb_array_len(VALUE)’
 rb_array_len(VALUE a)
 ^
Makefile:207: recipe for target 'dump.o' failed
make: *** [dump.o] Error 1
rake aborted!
Command failed with status (2): [make...]
/usr/lib/ruby/vendor_ruby/rake/file_utils.rb:66:in `block in create_shell_runner'
/usr/lib/ruby/vendor_ruby/rake/file_utils.rb:57:in `sh'
/usr/lib/ruby/vendor_ruby/rake/file_utils_ext.rb:37:in `sh'
/home/dfki.uni-bremen.de/rdominguez/rock/entern/05/.gems/gems/rake-compiler-0.8.3/lib/rake/extensiontask.rb:112:in `block (2 levels) in define_compile_tasks'
/usr/lib/ruby/2.3.0/fileutils.rb:128:in `chdir'
/usr/lib/ruby/2.3.0/fileutils.rb:128:in `cd'
/usr/lib/ruby/vendor_ruby/rake/file_utils_ext.rb:37:in `chdir'
/home/dfki.uni-bremen.de/rdominguez/rock/entern/05/.gems/gems/rake-compiler-0.8.3/lib/rake/extensiontask.rb:111:in `block in define_compile_tasks'
/usr/lib/ruby/vendor_ruby/rake/task.rb:240:in `block in execute'
/usr/lib/ruby/vendor_ruby/rake/task.rb:235:in `each'
/usr/lib/ruby/vendor_ruby/rake/task.rb:235:in `execute'
/usr/lib/ruby/vendor_ruby/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/usr/lib/ruby/vendor_ruby/rake/task.rb:172:in `invoke_with_call_chain'
/usr/lib/ruby/vendor_ruby/rake/task.rb:201:in `block in invoke_prerequisites'
/usr/lib/ruby/vendor_ruby/rake/task.rb:199:in `each'
/usr/lib/ruby/vendor_ruby/rake/task.rb:199:in `invoke_prerequisites'
/usr/lib/ruby/vendor_ruby/rake/task.rb:178:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/usr/lib/ruby/vendor_ruby/rake/task.rb:172:in `invoke_with_call_chain'
/usr/lib/ruby/vendor_ruby/rake/task.rb:201:in `block in invoke_prerequisites'
/usr/lib/ruby/vendor_ruby/rake/task.rb:199:in `each'
/usr/lib/ruby/vendor_ruby/rake/task.rb:199:in `invoke_prerequisites'
/usr/lib/ruby/vendor_ruby/rake/task.rb:178:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/usr/lib/ruby/vendor_ruby/rake/task.rb:172:in `invoke_with_call_chain'
/usr/lib/ruby/vendor_ruby/rake/task.rb:201:in `block in invoke_prerequisites'
/usr/lib/ruby/vendor_ruby/rake/task.rb:199:in `each'
/usr/lib/ruby/vendor_ruby/rake/task.rb:199:in `invoke_prerequisites'
/usr/lib/ruby/vendor_ruby/rake/task.rb:178:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/usr/lib/ruby/vendor_ruby/rake/task.rb:172:in `invoke_with_call_chain'
/usr/lib/ruby/vendor_ruby/rake/task.rb:201:in `block in invoke_prerequisites'
/usr/lib/ruby/vendor_ruby/rake/task.rb:199:in `each'
/usr/lib/ruby/vendor_ruby/rake/task.rb:199:in `invoke_prerequisites'
/usr/lib/ruby/vendor_ruby/rake/task.rb:178:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/usr/lib/ruby/vendor_ruby/rake/task.rb:172:in `invoke_with_call_chain'
/usr/lib/ruby/vendor_ruby/rake/task.rb:201:in `block in invoke_prerequisites'
/usr/lib/ruby/vendor_ruby/rake/task.rb:199:in `each'
/usr/lib/ruby/vendor_ruby/rake/task.rb:199:in `invoke_prerequisites'
/usr/lib/ruby/vendor_ruby/rake/task.rb:178:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/usr/lib/ruby/vendor_ruby/rake/task.rb:172:in `invoke_with_call_chain'
/usr/lib/ruby/vendor_ruby/rake/task.rb:165:in `invoke'
/usr/lib/ruby/vendor_ruby/rake/application.rb:150:in `invoke_task'
/usr/lib/ruby/vendor_ruby/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:106:in `each'
/usr/lib/ruby/vendor_ruby/rake/application.rb:106:in `block in top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:115:in `run_with_threads'
/usr/lib/ruby/vendor_ruby/rake/application.rb:100:in `top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:78:in `block in run'
/usr/lib/ruby/vendor_ruby/rake/application.rb:176:in `standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:75:in `run'
/usr/bin/rake:27:in `<main>'
Tasks: TOP => default => compile => compile:x86_64-linux-gnu => compile:roby_marshalling:x86_64-linux-gnu => copy:roby_marshalling:x86_64-linux-gnu:2.3.1 => tmp/x86_64-linux-gnu/roby_marshalling/2.3.1/roby_marshalling.so
```

**Comment by doudou** [comment]
Now, let's be clear. This is a very sad state of Rock, but `stable` is simply not forward compatible. If you intend to stick with `stable`, then you have to stick with what was available at the time (ruby ... 2.1 probably, autoproj v1, C++98).

What would be awesome is that you test the current RC so that we can release it. The silence to my email was ... deafening.

**Comment by doudou** [comment]
> > Now, let's be clear
> OK. I didn't intent to be unclear or annoying and I appreciate the tooling and the support a lot.

I did not mean anything by it. It's just that I wanted to reset both our expectations on this front... You've been very civil about this whole thing and I was not annoyed by it in any way.

> I honestly don't see how testing the current RC could help reconstructing the snapshot. In fact, a new release seems to set the difficulty to get the snapshot reconstructed even higher as basically everything would be obsolete. Testing a new release seems more like throwing stones to my own house!

What I meant is: you might have a less hard time updating your snapshot to the RC.

**Comment by Rauldg** [comment]
> What I meant is: you might have a less hard time updating your snapshot to the RC.

That was my first approach but I abandoned it as there are too many changes I should get up to date with and realized that it wouldn't make much sense. 

It starts with the package sets, then it goes to the base types and from there you basically have to update everything, ports changing names, different expected inputs... Actually, The reason why I made an snapshot was to have the possibility to get back to that software state which was functioning in that particular way.

I will give it a try with a docker image or a virtual machine. 

Regarding the Rock rc I will test it and provide feedback.

**Comment by doudou** [comment]
> It starts with the package sets, then it goes to the base types and from there you basically have to update everything, ports changing names, different expected inputs

Pity. I would have thought that un-pinning rock.core - while keeping the rest - would have minimal impact given how few user-visible changes happened on the toolchain.... Anyways...

**Comment by brean** [comment]
Hey, this problem still persists today, I just follow the official installation guide and got the same error. 
What exactly is the best solution for this if you just like to get a running ROCK installation? 
New rock users who just follow the installation guide will get this error message.

**Comment by 2maz** [comment]
changing to flavor 'master' will fix your issue.
@doudou how about making 'master' the default (at least for now?)

**Comment by doudou** [comment]
> @doudou how about making 'master' the default (at least for now?)

:+1: could you do it ?

**Comment by 2maz** [comment]
Suggested change: rock-core/package_set#137
