### ISSUE TITLE
roby-log exception

### ISSUE THREAD

**Issue by joaobrittoneto** [rock-core/tools-roby#78]
I was trying the do `roby-log display live-events.log` and got the follow error msg:

```
/home/joao/dev.bir.alpha/tools/roby/lib/roby/task_arguments.rb:237:in `block in merge!': cannot 
override task argument constant_pose_def: trying to replace constant_pose_def() by 
constant_pose_def(setpoint => {:x=>30.599914743564014, :y=>9.001469878241883, :z=>-0.2, 
:yaw=>-1.4352922724458748}) while serving exception_notification(#<DRobyID:1>, fatal, 
#<Roby::DRoby::V5::ExecutionExceptionDumper::DRoby:0x000001cac2e6d0>, 
#<Set:0x000001cbd8f118>) (ArgumentError)
	from /home/joao/dev.bir.alpha/tools/roby/lib/roby/task_arguments.rb:231:in `merge!'
	from /home/joao/dev.bir.alpha/tools/roby/lib/roby/task_arguments.rb:231:in `merge!'
	from /home/joao/dev.bir.alpha/tools/roby/lib/roby/droby/v5/droby_dump.rb:509:in `update'
	from /home/joao/dev.bir.alpha/tools/roby/lib/roby/droby/marshal.rb:147:in `block in find_local_object'
	from /home/joao/dev.bir.alpha/tools/roby/lib/roby/droby/marshal.rb:141:in `each'
	from /home/joao/dev.bir.alpha/tools/roby/lib/roby/droby/marshal.rb:141:in `find_local_object'
	from /home/joao/dev.bir.alpha/tools/roby/lib/roby/droby/marshal.rb:165:in `local_object'
	from /home/joao/dev.bir.alpha/tools/roby/lib/roby/droby/marshal.rb:88:in `block (2 levels) in load_groups'
	from /home/joao/dev.bir.alpha/tools/roby/lib/roby/droby/marshal.rb:87:in `each'
	from /home/joao/dev.bir.alpha/tools/roby/lib/roby/droby/marshal.rb:87:in `each_slice'
	from /home/joao/dev.bir.alpha/tools/roby/lib/roby/droby/marshal.rb:87:in `each'
	from /home/joao/dev.bir.alpha/tools/roby/lib/roby/droby/marshal.rb:87:in `map'
	from /home/joao/dev.bir.alpha/tools/roby/lib/roby/droby/marshal.rb:87:in `block in load_groups'
	from /home/joao/dev.bir.alpha/tools/roby/lib/roby/droby/marshal.rb:86:in `map'
	from /home/joao/dev.bir.alpha/tools/roby/lib/roby/droby/marshal.rb:86:in `load_groups'
	from /home/joao/dev.bir.alpha/tools/roby/lib/roby/droby/v5/droby_dump.rb:16:in `proxy'
	from /home/joao/dev.bir.alpha/tools/roby/lib/roby/droby/marshal.rb:182:in `local_object'
	from /home/joao/dev.bir.alpha/tools/roby/lib/roby/droby/v5/droby_dump.rb:183:in `proxy'
	from /home/joao/dev.bir.alpha/tools/roby/lib/roby/droby/marshal.rb:182:in `local_object'
	from /home/joao/dev.bir.alpha/tools/roby/lib/roby/droby/plan_rebuilder.rb:140:in `local_object'
	from /home/joao/dev.bir.alpha/tools/roby/lib/roby/droby/plan_rebuilder.rb:326:in `exception_notification'
	from /home/joao/dev.bir.alpha/tools/roby/lib/roby/droby/plan_rebuilder.rb:121:in `process_one_event'
	from /home/joao/dev.bir.alpha/tools/roby/lib/roby/droby/plan_rebuilder.rb:111:in `block in process_one_cycle'
	from /home/joao/dev.bir.alpha/tools/roby/lib/roby/droby/plan_rebuilder.rb:110:in `each'
	from /home/joao/dev.bir.alpha/tools/roby/lib/roby/droby/plan_rebuilder.rb:110:in `each_slice'
	from /home/joao/dev.bir.alpha/tools/roby/lib/roby/droby/plan_rebuilder.rb:110:in `process_one_cycle'
	from /home/joao/dev.bir.alpha/tools/roby/lib/roby/gui/plan_rebuilder_widget.rb:224:in `analyze'
	from /home/joao/dev.bir.alpha/tools/roby/lib/roby/gui/plan_rebuilder_widget.rb:242:in `analyze'
	from /home/joao/dev.bir.alpha/tools/roby/lib/roby/gui/plan_rebuilder_widget.rb:205:in `open'
	from /home/joao/dev.bir.alpha/tools/roby/lib/roby/gui/log_display.rb:174:in `open'
	from /home/joao/dev.bir.alpha/tools/roby/lib/roby/cli/display.rb:51:in `block in file'
	from /home/joao/dev.bir.alpha/tools/roby/lib/roby/cli/display.rb:166:in `with_display'
	from /home/joao/dev.bir.alpha/tools/roby/lib/roby/cli/display.rb:50:in `file'
	from /home/joao/dev.bir.alpha/tools/roby/lib/roby/cli/log.rb:268:in `display'
	from /home/joao/.autoproj/gems/ruby/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /home/joao/.autoproj/gems/ruby/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/joao/.autoproj/gems/ruby/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /home/joao/.autoproj/gems/ruby/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /home/joao/dev.bir.alpha/tools/roby/bin/roby-log:4:in `<main>
```
I also tried `roby-log repair live-events.log` but it seems to have no effect. 
With `roby-log decode live-events.log` it's possible to get the events till the error msg appears. But the events after that are not reachable.
```
/home/joao/dev.bir.alpha/tools/roby/lib/roby/task_arguments.rb:237:in `block in merge!': cannot 
override task argument constant_pose_def: trying to replace constant_pose_def() by 
constant_pose_def(setpoint => {:x=>30.599914743564014, :y=>9.001469878241883, :z=>-0.2, 
:yaw=>-1.4352922724458748}) while serving exception_notification(#<DRobyID:1>, fatal, 
#<Roby::DRoby::V5::ExecutionExceptionDumper::DRoby:0x00000007293540>, 
#<Set:0x0000000723af80>) (ArgumentError)
```

The last lines of `roby-log decode` is:
```
2017-11-30 11:23:23 -0300 timepoint  #<DRobyID:2>  MAIN  scheduler
2017-11-30 11:23:23 -0300 timepoint_group_start  #<DRobyID:2>  MAIN  poll_state_events
2017-11-30 11:23:23 -0300 timepoint_group_end  #<DRobyID:2>  MAIN  poll_state_events
2017-11-30 11:23:23 -0300 timepoint_group_start  #<DRobyID:2>  MAIN  syskit:connection_management_update
2017-11-30 11:23:23 -0300 timepoint_group_end  #<DRobyID:2>  MAIN  syskit:connection_management_update
2017-11-30 11:23:23 -0300 timepoint_group_start  #<DRobyID:2>  MAIN  syskit:apply_requirement_modifications
2017-11-30 11:23:23 -0300 timepoint_group_end  #<DRobyID:2>  MAIN  syskit:apply_requirement_modifications
2017-11-30 11:23:23 -0300 timepoint_group_end  #<DRobyID:2>  MAIN  event_propagation_phase
2017-11-30 11:23:23 -0300 timepoint_group_start  #<DRobyID:2>  MAIN  error_handling_phase
2017-11-30 11:23:23 -0300 timepoint  #<DRobyID:2>  MAIN  structure_check
2017-11-30 11:23:23 -0300 timepoint  #<DRobyID:2>  MAIN  exception_propagation
2017-11-30 11:23:23 -0300 exception_notification  #<DRobyID:1>  fatal  #<Roby::DRoby::V5::ExecutionExceptionDumper::DRoby:0x00000007293540>  #<Set:0x0000000723af80>
```

Is it a problem with the log itself, or with roby-log?

**Comment by doudou** [comment]
Hard to say, really.

Do you think you could send me the log ?

**Comment by doudou** [comment]
... I'm not sure what happened with this ... Closing for now, comment if there's something to do.

**Comment by joaobrittoneto** [comment]
ops, I forgot this.
No problem. If I see other bug like this I'll report here.
